### ISSUE TITLE
Fix image on arm64

### ISSUE THREAD

**Issue by dwt** [Icinga/docker-icingadb#46]
since I've switched to an apple silicon notebook, I have the problem that this image doesn't work anymore. Docker does start it a amd64 compatibility environment (Qemu) that tries to do it's thing, but sadly fails.

```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

Interestingly all the other Icinga images seem to work fine under emulation.

It may be easy to fix this (and I'm willing to help debug this) but it may be a better solution to build a multi-platform image that supports arm64 natively. This should also allow for much better performance.

This seems to be some documentation on [how to build multi arch images](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) ([buildx documentation](https://docs.docker.com/buildx/working-with-buildx/)).  `docker buildx --platform ...` seems to be the way to go.

**Comment by Al2Klimov** [comment]
Sukhwinder, please confirm the error.

**Comment by sukhwinder33445** [comment]
Confirmed, container is running, but shows the same log as above.

**Comment by mocdaniel** [comment]
I can confirm this, too. I built a workaround `Dockerfile` including the relatively new [`heredocs` inline-scripting functionality](https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/), which looks like this @dwt :

```Dockerfile
# syntax=docker/dockerfile:1.3-labs
# Icinga DB Docker image | (c) 2020 Icinga GmbH | GPLv2+

FROM golang:alpine as entrypoint

RUN <<EOF
#! /usr/bin/env sh
if [ $(uname -m) != "x86_64" ]
then
  apk add wget xz tar
  wget -O upx.tar.xz https://github.com/upx/upx/releases/download/v3.96/upx-3.96-arm64_linux.tar.xz
  tar xf upx.tar.xz
  mv upx-3.96-arm64_linux/upx /usr/bin/upx
else
  apk add upx
fi
rm -vf /var/cache/apk/*
EOF

COPY entrypoint /entrypoint

WORKDIR /entrypoint
ENV CGO_ENABLED 0

RUN ["go", "build", "-ldflags", "-s -w", "."]
RUN ["upx", "entrypoint"]


FROM alpine as base
RUN ["mkdir", "/empty"]
COPY rootfs /rootfs
RUN ["chmod", "-R", "u=rwX,go=rX", "/rootfs"]


FROM scratch

COPY --from=base /rootfs/ /
COPY --from=base --chown=icingadb:icingadb /empty /etc/icingadb
COPY --from=entrypoint /entrypoint/entrypoint /entrypoint
COPY icingadb *sql.schema.sql.bz2 /

USER icingadb
CMD ["/entrypoint"]
```

This Dockerfile needs to be build via `docker buildx build -t myname/myimage:v0.0.1 --load .` in order to build and load it to the local Docker image registry.

I'd be happy to open a PR and update the README if this is an acceptable solution, but I think having properly built `multiarch` images provided by Icinga would be the better way to go.

**Comment by Al2Klimov** [comment]
Actually the container doesn’t need upx, I did this because I can.

**Comment by mocdaniel** [comment]
In this case, building multiarch images should be even easier, this could e.g. be done directly via Github Actions:

```yaml
name: publish-docker-images

on:
  release:
    types:
    - published
  workflow_dispatch: {}

jobs:
  push-images:
    name: Push images to registry
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          icinga/docker-icingadb
        # generate Docker tags based on the following events/attributes
        tags: |
          type=semver,pattern={{version}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up BuildX
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: icinga/icingadb
```
